### ISSUE TITLE
Paper button with "raised" attribute will get wrong elevation if it becomes enabled while keyboard is focused

### ISSUE THREAD

**Issue by mm-gmbd** [PolymerElements/paper-button#100]
Kind of an odd set of steps to reproduce, but I can reproduce nonetheless:

- https://jsfiddle.net/7mhx3gpn/1/
- Click the button, button becomes disabled (don't click elsewhere on page)
- Switch applications away from Chrome and then back to Chrome (in < 10s)
- Now, button has class "keyboard-focus"
- When timer fires to re-enable button, with "keyboard-focus" applied, the elevation is now higher than "1"

**Comment by keanulee** [comment]
Hi @mm-gmbd,

I think this is a symptom of #98 (where disabling a button doesn't cause it to lose focus). I have a patch for that in the works, but I'm going to mark this issue as a duplicate and close it.
