### ISSUE TITLE
Polymer dom does not normalize paper-button's localTarget

### ISSUE THREAD

**Issue by Typel** [PolymerElements/paper-button#106]
Given the following situation:

    <paper-button on-tap="_doSomething" id="button">Click Here <iron-icon id="icon" icon="icons:expand-more"></iron-icon></paper-button>
    ...
    app._doSomething = function(e) {
      console.log(Polymer.dom(e).localTarget.id);
    };

Clicking on the button in various locations logs an assortment of values to the console, back and forth between "button" and "icon" depending on where the button is clicked. It was my understanding that Polymer.dom should normalize the tap's source to the element's underlying button as it does with paper-fab. Is this normal behavior for paper-button or should this be fixed?

Thank you.

**Comment by keanulee** [comment]
@Typel This is normal behavior - the `<iron-icon>` is in the light DOM (i.e. _you_ created this `<iron-icon>` element and passing it to `<paper-button>`), so it is local to you and that's what the API should return (if you did indeed click the icon). In `<paper-fab>`'s case, the icon is in paper-fab's local DOM (i.e. you didn't declare the iron-icon - that is an implementation detail of paper-fab) so you shouldn't see that in the normalized event.
