### ISSUE TITLE
paper-button accessibility issues: Windows specific 

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/paper-button#11]
Note: Please note that the first rounds of accessibility testing / issue reporting were done using Chrome on Mac with VoiceOver enabled, as well as Chrome on Chrome OS with ChromeVox enabled. This next round was done on the Windows platform, on both Chrome and Firefox with the NVDA screen reader enabled. Once the team addresses the issues across platforms and screen readers, we will also do a final test using Windows and the JAWS screen reader, a heavily used combo that certainly needs to work smoothly. 

Issues: 

Chrome / NVDA: When navigating linearly and I reach the row of buttons, NVDA reads all the buttons in the row at once, as opposed to being able to use the arrow key to navigate to each individually. 

Firefox /  NVDA: When navigating linearly, when I navigate left to right through each button, NVDA announces ""blank"" between each button, as if it's picking up the blank space between the buttons as a separate item. This does not occur when navigating through the headings, only the buttons. This seems to be Firefox specific.

**Comment by blasten** [comment]
**Chrome / NVDA: When navigating linearly and I reach the row of buttons, NVDA reads all the buttons in the row at once, as opposed to being able to use the arrow key to navigate to each individually.**

I don't see what could be causing this issue. Is it in the first row only?

**Comment by lpalmaro** [comment]
I just retested and this issue is no longer occurring with NVDA.

**Comment by blasten** [comment]
great
