### ISSUE TITLE
Focus style doesn't match material spec

### ISSUE THREAD

**Issue by cleercode** [PolymerElements/paper-button#111]
### Expected outcome
Focusing the button using the tab key should give the button a background color of either the fill color or black (unclear from the wording of the spec) at 12% opacity: https://www.google.com/design/spec/components/buttons.html

### Actual outcome
Focusing the button makes the font bold.

Note: The bold font weight is especially difficult to distinguish from the normal state if the normal state is made to use medium instead of regular font weight, as the material spec also specifies.

### Live Demo
https://elements.polymer-project.org/elements/paper-button?view=demo:demo/index.html

**Comment by cleercode** [comment]
Should have searched first: 
https://github.com/PolymerElements/paper-button/issues/94
https://github.com/PolymerElements/paper-button/issues/95

That said, it'd be good to see some consistency on this between Polymer and MD.

**Comment by keanulee** [comment]
#95 pretty much sums up why we haven't done this. For now we suggest you override it if that's what you want (knowing why we did this in the first place).
