### ISSUE TITLE
can not click element from "on-transitionend" callback

### ISSUE THREAD

**Issue by NicolasRannou** [PolymerElements/paper-button#117]
### Description

Can not click on an element from "on-transitionend" callback.
```
...
<paper-button raised on-transitionend="clickInput">Load data</paper-button>
<input type="file" id="input" multiple="">
...
clickInput: function(){
  // not working
  this.$.input.click();
}
```
If I use on-tap instead of on-transtionend the callback works properly.

### Expected outcome

Target element should be clicked.

### Actual outcome

click() doesn't do anything but this.$.input appear to return a well formatted element.

### Live Demo
https://plnkr.co/edit/FvNnn4m1RroAQSoy7eQD?p=preview

### Steps to reproduce

1. Open console
2. Click on button
3. Callback is called multiple times but nothing happens
4. Replace on-transitionend by on-tap on the <paper-button>
5. It works as expected.

### Browsers Affected
- [x] All

**Comment by keanulee** [comment]
You can't trigger file input from non-user interaction - for example, see http://jsbin.com/qusuqunece/edit?html,output

**Comment by NicolasRannou** [comment]
👍
