### ISSUE TITLE
material design spec audit - few changes needed

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-button#12]
* Typography seems like it might be off - font too large and/or not the right roboto? This might just be in the demo but should be right.
* Pressed state might have to be a little higher.
* Decision handed down from design: button should NOT stay focused after press, unless it was focused prior to press.
* Pressed state height should be 2x the focus state height. We should exaggerate both if needed for a11y.

**Comment by blasten** [comment]
It's mostly fixed except for  "... button should NOT stay focused after press"
The main reason is that after press, the button is automatically focused. As far as I know, this is the default behavior of most controls. Once tapped, it's focus is transferred. Correct me if I'm wrong @cdata.

**Comment by cdata** [comment]
@tjsavage @blasten To be clear, design is referring to the focus *visual*, not the actual state of being *focused*, correct? If so, this should be easy to change for everything in https://github.com/PolymerElements/iron-behaviors.

**Comment by blasten** [comment]
all should be fixed now!
