### ISSUE TITLE
Raised buttons inverted colors

### ISSUE THREAD

**Issue by bvhme** [PolymerElements/paper-button#121]
Hey, kind of a feature request:

The raised buttons as they are displayed in the [Material Design style guide](https://material.google.com/components/buttons.html#) mostly display another kind of raised button. One where the `--primary-color` is the background color and I would love to be able to use these in my components. Sadly `paper-button` has no support for such styling.

![raised inverted color button](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B7WCemMG6e0VbDh6YmNiYVc3SHM/components_buttons_usage2.png)

Something like a `primary` attribute or something similar would be great.

Furthermore if I use `--paper-button` to set this styling I can't seem to figure out what variable to use for the text-color that will work across light and dark themes.

Thanks

**Comment by keanulee** [comment]
You can specify custom background/text colors using custom properties (see bottom examples at https://elements.polymer-project.org/elements/paper-button?view=demo:demo/index.html&active=paper-button), but there's no "magic" way to just swap the colors. You'll probably have to pick different text colors for light and dark themes.
