### ISSUE TITLE
hidden attribute does not work for paper-button used inside shadow dom

### ISSUE THREAD

**Issue by coreyfarrell** [PolymerElements/paper-button#122]
### Description
paper-button does not respect the hidden attribute when used inside a shadow root.

### Expected outcome
The hidden attribute should cause display:none to apply.

### Live Demo
https://jsbin.com/goyivozuju/edit?html,output

Related to PolymerElements/paper-input#397.

**Comment by keanulee** [comment]
Duplicate #119
