### ISSUE TITLE
paper-button lacks ripple effect on reattach

### ISSUE THREAD

**Issue by alxhub** [PolymerElements/paper-button#13]
When reattaching a paper-button to the DOM, its ripple effect no longer functions when the button is clicked. All other button functionality seems to be okay - in particular, the button itself gets its CSS classes when the mouse is held down.

**Comment by justinfagnani** [comment]
@cdata the but I was talking about

**Comment by blasten** [comment]
I was able to replicate this issue in Firefox, it seems to work fine in Chrome 42 and Canary.  What browser were you using?

**Comment by cdata** [comment]
I cannot reproduce this issue in Firefox. Please re-open if you think it's still happening!
