### ISSUE TITLE
update to latest iron-flex-layout

### ISSUE THREAD

**Issue by jab** [PolymerElements/paper-button#133]
Noticed PolymerElements/paper-styles#105, and that paper-button also needs the same treatment but has no corresponding issue, so thought I'd create one in case helpful.

Thanks for the great work on Polymer!

**Comment by notwaldorf** [comment]
`paper-button` isn't using any of the `/deep/` classes, and it's already using the mixins [version](https://github.com/PolymerElements/paper-button/blob/master/paper-button.html#L12) of `iron-flex-layout`, so it doesn't need any updates.

**Comment by jab** [comment]
Sorry about that, I was in the middle of upgrading a bunch of elements and thought I saw deprecation warnings printed due to both paper-styles and paper-button including the non-mixins version, but I must have been looking at an out-of-date console or something. Sorry for the noise!

**Comment by notwaldorf** [comment]
No worries!
