### ISSUE TITLE
[2.0-preview] button content is not center aligned

### ISSUE THREAD

**Issue by cdata** [PolymerElements/paper-button#136]
![image](https://cloud.githubusercontent.com/assets/240083/19127226/fc92d7b0-8af2-11e6-8fd5-4c74bff32c26.png)

**Comment by keanulee** [comment]
paper-button 2.0 adds the `.paper-material` class (which applies `display: block` through `:host(.paper-material)`), but paper-button relies on `display: inline-flex` (set by `@apply --layout-inline` on `:host`) to center content. Perhaps paper-material should not set the CSS `display` property.

https://github.com/PolymerElements/paper-button/commit/1895fb33eaa4748065b709dd8373d5b510c14931#diff-a266820d4466f8f0a52ce98f7e191d62R169

**Comment by notwaldorf** [comment]
Fixed in  73bf77e9ec05
