### ISSUE TITLE
Problem with Safari

### ISSUE THREAD

**Issue by rokity** [PolymerElements/paper-button#137]
If you go with safari in [demo](https://elements.polymer-project.org/elements/paper-button?view=demo:demo/index.html) page of component .
You can't see the content of the paper-button.
Why? It's only for my Safari ? I have the last version of Safari (10.0.1).
Why I can't see the content of the paper-button ??

**Comment by keanulee** [comment]
@rokity Can't reproduce with Safari 10.0.1 on macOS Sierra:
![image](https://cloud.githubusercontent.com/assets/1319720/20279857/11c17f20-aa5f-11e6-8956-36572541d192.png)
