### ISSUE TITLE
document.createElement('paper-button') DOMException

### ISSUE THREAD

**Issue by jaichandra** [PolymerElements/paper-button#144]
### Description

With the latest 2.0-preview branch, if I do `document.createElement('paper-button');`, I am getting a DOMException.

This seems to be caused by the below code in `paper-button`.
```
created: function() {
        this.classList.add('paper-material');
      },
```

Changing that to use `connectedCallback` seems to fix the issue.

### Expected outcome

No Error

### Actual outcome

DOMException:
```
Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes
    at <anonymous>:1:10
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by WoodyWoodsta** [comment]
Confirmed. See point five of [section 2.2 of the spec](https://www.w3.org/TR/custom-elements/#custom-element-conformance).

**Comment by notwaldorf** [comment]
my 2 cents is that changing that to `connectedCallback` is fine

**Comment by justincy** [comment]
Changing it to `connectedCallback` didn't work for me (the error went away but the style's weren't added). I had to change it to `attached`.

**Comment by jaichandra** [comment]
@justincy thats correct. I have the PR with `attached` here #145

**Comment by notwaldorf** [comment]
Closing, as we're no longer adding the `paper-material` class on the host
