### ISSUE TITLE
Keyboard enter or space does not trigger link

### ISSUE THREAD

**Issue by kennethklee** [PolymerElements/paper-button#147]
### Description

When used with an anchor link, a pressing `enter` or `space` on a keyboard while focused does not trigger the anchor.

### Expected outcome

Pressing `enter` or `space` with the button focused should trigger the parent anchor link.

### Actual outcome

Nothing happens.

### Steps to reproduce

1. Put an anchor element, `<a>`.
2. Put a child `<paper-button>` element.
3. Focus the `<paper-button` element.
4. Press `enter` or `space`.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by kennethklee** [comment]
Hopefully that PR  is good. ^

**Comment by abdonrd** [comment]
The last demo show you how to use the paper-button as an anchor:
[webcomponents.org/element/PolymerElements/paper-button/demo/demo/](https://www.webcomponents.org/element/PolymerElements/paper-button/demo/demo/)

```html
<a href="https://www.polymer-project.org" tabindex="-1">
  <paper-button raised>Polymer Project</paper-button>
</a>
```

**Comment by kennethklee** [comment]
oh you're right it works all of a sudden. i wonder why it wasn't working on my computer before. nor on my project. anyway closing. closing PR too.

**Comment by orjantufte** [comment]
<a on-tap="_openDocument" href="javascript:">Try this</a>

**Comment by orjantufte** [comment]
```HTML
<a on-tap="_openDocument" href="javascript:">Try this</a>
```
