### ISSUE TITLE
Button is not disabled with disabled attribute #2.0-preview

### ISSUE THREAD

**Issue by fairsayan** [PolymerElements/paper-button#149]
### Description
Unable to disable paper button with #2.0-preview branch

### The Code
```
<paper-button id="login" on-tap="_onTapLoginButton" autofocus disabled>{{localize('Login')}}</paper-button>
```
...
```
_onTapLoginButton () {
  console.info('aa');
}
```
The 'aa' string is always printed

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
Looks disabled in the [demo](http://polygit.org/polymer+v2.0.0-rc.4/webcomponentsjs+webcomponents+v1.0.0-rc.8/shadycss+webcomponents+1.0.0-rc.5/paper*+polymerelements+:2.0-preview/iron*+polymerelements+:2.0-preview/app*+polymerelements+:2.0-preview/neon*+polymerelements+:2.0-preview/components/paper-button/demo/index.html?wc-shadydom=true) so I think this is an old issue
