### ISSUE TITLE
Import should be paper-material-styles for 2.0 preview

### ISSUE THREAD

**Issue by rkief** [PolymerElements/paper-button#162]
### Description
<link rel="import" href="../paper-styles/element-styles/paper-material.html">

### Expected outcome
<link rel="import" href="../paper-styles/element-styles/paper-material-styles.html">

### Actual outcome

Request URL:http://127.0.0.1:8081/bower_components/paper-styles/element-styles/paper-material.html
Request Method:GET
Status Code:404 Not Found

### Steps to reproduce
1. Using 2.0 preview

### Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by mflorence99** [comment]
In addition to the import ~line 14, which should read:

```html
<link rel="import" href="../paper-styles/element-styles/paper-material-styles.html">
```

the `style` ~line 86 must also change:

```html
<style include="paper-material-styles">
```

**Comment by mflorence99** [comment]
Ok, so now I see it _is_ coded this way in the master branch. So I overcame my build problem by temporarily changing my `bower.json`:

```json
...
"paper-button": "PolymerElements/paper-button#master",
...
```

**Comment by kownacki** [comment]
@mflorence99 It didn't work for me. I have no errors, but Polymer seems to not work and doesn't update properties.

**Comment by valdrinkoshi** [comment]
This should be fixed in the latest 2.x version \o/ closing this
