### ISSUE TITLE
Cannot remove underline when used with <a>

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/paper-button#167]
When wrapped by a <a> tag to become a link, it is impossible to remove the underline. Changing the color works fine. This also shows on the demo page.

```
   a paper-button,
    a:active paper-button,
    a:visited paper-button {
      color: #000;
      text-decoration: none !important;
    }
```

**Comment by keanulee** [comment]
@kenchris You should set `text-decoration: none` on the `a` selector instead:

```css
a { text-decoration: none }
```

**Comment by valdrinkoshi** [comment]
Closing this as solution was provided
