### ISSUE TITLE
Wrong install command in webcomponents page

### ISSUE THREAD

**Issue by zamuset** [PolymerElements/paper-button#185]
### Description

Just a quick FYI for newbies like myself, the install command is wrong in the webcomponents page and it throws an error when you try to install it
### Expected command
**bower** install --save PolymerElements/paper-button

### Actual command
**npm** install --save PolymerElements/paper-button

**Comment by keanulee** [comment]
For 2.x (current stable) versions it's still bower, but for the upcoming 3.x version it should be `npm i @polymer/paper-button`.
