### ISSUE TITLE
'noink' should be a boolean property

### ISSUE THREAD

**Issue by dzhioev** [PolymerElements/paper-button#19]
I think 'noink' should be defined as `<paper-button>`'s boolean property which is reflected to an attribute.
That'll make 'noink' consistent with other properties/attributes of `<paper-button>` (e.g. 'raised', 'disabled').

**Comment by cdata** [comment]
Thanks for reporting, I will take a look.

**Comment by cdata** [comment]
This behavior has been updated, and the bug may no longer be relevant. Please re-open if you think it is!
