### ISSUE TITLE
Polymer.PaperButtonBehavior documentation not found.

### ISSUE THREAD

**Issue by grokys** [PolymerElements/paper-button#27]
Clicking the Polymer.PaperButtonBehavior at the bottom of the paper-button docs gives the message

> No documentation available for Polymer.PaperButtonBehavior

**Comment by samccone** [comment]
https://elements.polymer-project.org/elements/paper-behaviors?active=Polymer.PaperButtonBehavior

this has been resolved :+1: :+1: to close 

cc @notwaldorf

**Comment by samccone** [comment]
@frankiefu what resolved this¿
