### ISSUE TITLE
Docs: how to use paper-button as a link

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/paper-button#35]
Element doc should include an example of wrapping the button in an anchor so it can be used as a link.

**Comment by SayChunKim** [comment]
+1

**Comment by gulyasfeccferenc** [comment]
+1

**Comment by ebidel** [comment]
Here's one way:

```
<paper-button onclick="addNewFeature(this)"></paper-button>

function addNewFeature(el) {
  // Wait for ripple to finish.
  el.addEventListener('transitionend', function(e) {
    location.href = '/admin/features/new';
  });
}```

You could also use a declarative `<a>` and prevent the click, wait for the ripple to finish, and then do the redirect.

**Comment by robdodson** [comment]
Or use the `noink` attr if you aren't a fan of the ripple

**Comment by kaycebasques** [comment]
:+1: AKA +1

**Comment by abdonrd** [comment]
With the @ebidel way, we need to write a function...

We can have something like this?

```html
<paper-button href="https://www.polymer-project.org"></paper-button>
```

**Comment by ebidel** [comment]
I don't think href makes sense on paper-button, but it would be nice if paper-button knew it had a anchor children and had a feature that de-janked the ripple for you.

**Comment by abdonrd** [comment]
@ebidel like this?

```html
<paper-button>
    <a href="https://www.polymer-project.org">Polymer website</a>
</paper-button>
```

**Comment by ebidel** [comment]
Yes. It would JustWork:registered:

**Comment by abdonrd** [comment]
@ebidel and we have the same problem with the `paper-icon-button`.
It would be something like this? An empty `<a>` is strange.

```html
<paper-icon-button icon="polymer">
    <a href="https://www.polymer-project.org"></a>
</paper-icon-button>
```

**Comment by abdonrd** [comment]
@robdodson @ebidel do you have any news about this?

**Comment by cdata** [comment]
After thinking about this for a bit, I believe the ideal we should strive for is this form:

```html
<a href="https://www.polymer-project.org">
  <paper-button>Polymer website</paper-button>
</a>
```

However, there may be problems with this form (e.g., a parent expects a specific kind of child, so wrapping is not an option). Are there any known conditions that you guys have run into where this would not work?

> And if we use a declarative <a>, we lost the ripple

[I tested this](https://output.jsbin.com/suwoma) and the ripple seems to work fine in this condition.

**Comment by cdata** [comment]
@robdodson @ebidel @abdonrd ^

**Comment by robdodson** [comment]
That looks fine to me. I would maybe put noink on the button to get rid of
the ripple so it doesn't jank the page.

**Comment by abdonrd** [comment]
Thanks @cdata!

I can you show an use of case when we have problems: http://jsbin.com/tevugezaje
We have a small problem, easily solved with CSS.
But try to use the `tab` key and see the focus behavior. :(

**Comment by keanulee** [comment]
Added an example of this in #91. I decided to leave out the `noink` attribute since it's nice to see the ripple effect when the user `mousedown`s (navigation doesn't occur until `mouseup`).

**Comment by abdonrd** [comment]
@keanulee check the behavior with focus. :/

First tab:
<img width="524" alt="screen shot 2016-01-21 at 20 17 42" src="https://cloud.githubusercontent.com/assets/1007051/12491560/1726e45a-c07c-11e5-99b8-f446f415f52a.png">

Second tab:
<img width="533" alt="screen shot 2016-01-21 at 20 17 50" src="https://cloud.githubusercontent.com/assets/1007051/12491562/19842078-c07c-11e5-99f8-50c73ef1bfa8.png">

**Comment by keanulee** [comment]
Ah yes, that is an issue. Easy way to fix this is to add `tabindex="-1"` to the `<a>` tag. `<paper-button>` would still be able to receive focus, and you can still navigate. I'll add this to #91. Thanks @abdonrd

**Comment by abdonrd** [comment]
Nice @keanulee! Your welcome!

**Comment by keanulee** [comment]
Example has been added in #91

**Comment by abdonrd** [comment]
@keanulee It would be great if you add another example waiting to finish the ripple effect before opening the link. :blush:
