### ISSUE TITLE
Ink doesn't match the button area when used in horizontal layout

### ISSUE THREAD

**Issue by mrdewitt** [PolymerElements/paper-button#37]
Sample code:

```
<div class="horizontal layout">
  <paper-input></paper-input>
  <paper-button id="b" raised>REPLY</paper-button>
</div>
```

Screenshot while clicking: 
![image](https://cloud.githubusercontent.com/assets/1316814/8994283/4b31a6d2-36bf-11e5-89d5-c388d7f11b80.png)

**Comment by bicknellr** [comment]
I haven't been able to repro this; do you have a live test case you could link to?

**Comment by mrdewitt** [comment]
Can't seem to repro this on recent versions of Polymer.
