### ISSUE TITLE
Use custom prop instead of ::shadow for styling ripple color

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-button#39]
We should move away from `::shadow`:

![screen shot 2015-07-31 at 11 06 12 am](https://cloud.githubusercontent.com/assets/238208/9014022/907004ea-3774-11e5-86d9-77bce4beb13c.png)

**Comment by blasten** [comment]
+1

**Comment by notwaldorf** [comment]
I've opened https://github.com/PolymerElements/paper-button/pull/50 to deal with this

**Comment by notwaldorf** [comment]
I've opened https://github.com/PolymerElements/paper-button/pull/50 to fix this
