### ISSUE TITLE
Pressing enter key doesn't work for on-tap events

### ISSUE THREAD

**Issue by Mygod** [PolymerElements/paper-button#41]
Changing `on-tap` to `on-click` resolves the problem though. Should I use `on-click` for `paper-button`s?

**Comment by cdata** [comment]
Thanks for reporting. I believe that this was related to https://github.com/Polymer/polymer/issues/2212 in Polymer core. Let me know if there is still a problem after the fix lands in Polymer and re-open if it still happens.
