### ISSUE TITLE
Windows 10 / Edge / InternetExplorer

### ISSUE THREAD

**Issue by azakus** [PolymerElements/paper-button#44]
_From @ARMistice on August 14, 2015 15:50_

On Windows 10 with InternetExplorer / Edge

https://elements.polymer-project.org/elements/paper-button?view=demo:demo/index.ht

Changeing the frame size or clicking buttons make everything flicker.
Seems to be a problem with the "ripple" effects

![image](https://cloud.githubusercontent.com/assets/312925/9277826/dbf9214c-42ac-11e5-870b-cdb7ba24e69b.png)

_Copied from original issue: Polymer/polymer#2275_

**Comment by azakus** [comment]
I can't seem to reproduce in Win10/Edge on either the catalog site, nor the demo.

**Comment by ARMistice** [comment]
Its on Windows 10 Microsoft Edge 20.10240.16384.0 ... all up to date .. the buttons with ripple and shadow do not work correct.

Totally reproducable ... like you can see in the image

Filed a Bug to Microsoft perhaps its their fault ;)

**Comment by azakus** [comment]
Sorry, have the same Edge version and cannot reproduce this behavior. Maybe something particular about your machine is causing problems? Do the demos also seem to not work in Chrome or Firefox for you?

**Comment by etinin** [comment]
I am having the same issue. Everything works fine in chrome, but things get very strange in the final version of Edge.
There are several interactions with the page that will screw up the style, but this way seems to be more reproducible: Make a simple form with paper-inputs, when you change to the paper-inputs, the mixins applied to the paper-button will get very strange.
No console errors whatsoever.

CORRECT RENDERING ON PAGE LOAD:
![image](https://cloud.githubusercontent.com/assets/173691/9495549/7d7734a8-4be2-11e5-956e-0168b150806a.png)

PAPER-INPUT SELECTED:
![image](https://cloud.githubusercontent.com/assets/173691/9495568/9c61ab46-4be2-11e5-8c94-9c3c365a019f.png)

**Comment by cdata** [comment]
I also cannot reproduce this problem. If you can provide a live test case in a JSBin of something going wrong, we will happily take a look. Please re-open if this is continuing to cause problems!

**Comment by ARMistice** [comment]
You don't need a JSBin .. simply use:

https://elements.polymer-project.org/elements/paper-button?active=paper-button&view=demo:demo/index.htm

and then click on the "Raised (blue) OK" Button (with checkmark) and watch the "X" below in the CANCEL button. It changes color in a strange way (has to do with the "fill effect")

Also a click on the "Toggleable NOINK" button sometimes changes the color of the "COLORFUL" below. 

I would belive this is a bug of Edge and not of Polymer, but strange anyway.
