### ISSUE TITLE
Feature Request: Thin buttons as per material design.

### ISSUE THREAD

**Issue by barischj** [PolymerElements/paper-button#47]
`<paper-button thin>hi</paper-button>`

See a thin button here:
https://www.google.com/design/spec/components/buttons.html#buttons-usage

**Comment by notwaldorf** [comment]
@jbarischr Which button are you talking about in particular? The flat ones, without the background?

**Comment by jbarischr** [comment]
Here's a direct link to an image from that page:
https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7VEdpenhQNFJRZm8/components_buttons_usage2.png

Actually the Polymer demo too:
https://elements.polymer-project.org/elements/paper-button?view=demo:demo/index.html

However whenever I implement them they seem to be taller and less wide.
Such as:
http://i.imgur.com/myG018H.png

**Comment by notwaldorf** [comment]
@jbarischr Can you reproduce this in a jsbin? I think there's some styles that are getting applied incorrectly, but I can't really tell unless I look at some code :)

**Comment by cdata** [comment]
Hi, I'm going to close this issue for now. If someone can provide a more concrete request, we will definitely re-open and consider it!
