### ISSUE TITLE
Consider optimizing performance

### ISSUE THREAD

**Issue by sorvell** [PolymerElements/paper-button#48]
Since users often create many instances of this element, it will especially benefit from performance optimization. Consider lazily creating optional or user initiated functionality (e.g. paper-ripple), leveraging behaviors over composition (e.g. paper-material), streamlining styling, and eliminating or simplifying features (e.g. behaviors)

**Comment by ebidel** [comment]
Here are two immediate wins:
- `<paper-ripple>` should under a `<template is="dom-if" if="{{!noink}}">` so it's only created when necessary
- `<paper-material>` should only be created if `raised` is `true`.

**Comment by sorvell** [comment]
Yup, but lan is to imperatively create `paper-ripple`. The `dom-if` is overkill in this case. Then `paper-material` can be decomposed to a behavior + css module.
