### ISSUE TITLE
No documentation available for Polymer.PaperButtonBehavior

### ISSUE THREAD

**Issue by CSEMike** [PolymerElements/paper-button#49]
So I am told by the docs here:
https://elements.polymer-project.org/elements/paper-button

The documentation for an element as basic as a button should be at least complete and ideally  sprawling, overflowing with examples.

**Comment by cdata** [comment]
Thanks for the feedback! Do you have any particular types of examples in mind?

Our docs have been updated to surface behavior implementation in the element docs where it is relevant. So, you should be able to find all the information you need in the docs for `paper-button`.

**Comment by CSEMike** [comment]
Looks good. Thanks!
