### ISSUE TITLE
Trying to install via Bower; keep getting EINVALID error for paper-behaviors.

### ISSUE THREAD

**Issue by ConAntonakos** [PolymerElements/paper-button#51]
Any idea why I keep getting this error?
![screen shot 2015-09-03 at 3 23 22 pm](https://cloud.githubusercontent.com/assets/1504302/9668488/c6e4e9d2-524f-11e5-9375-c620564c4d35.png)

Current `bower.json` dependencies:
![screen shot 2015-09-03 at 3 22 36 pm](https://cloud.githubusercontent.com/assets/1504302/9668469/abcdc4ca-524f-11e5-93e3-4b831d347d74.png)

I'm using bower version 1.5.2.

**Comment by ConAntonakos** [comment]
Oddly, it might be a problem with the new bower version. I downgraded to 1.3.9, and bower seems to be functioning better. I'll keep testing it.

**Comment by cdata** [comment]
Sorry, but I cannot reproduce this issue. Please re-open if you can reproduce the issue with the latest bower (I am using `1.6.3`).
