### ISSUE TITLE
On Safari, the ripple effect overflows the button round corner

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-button#6]
Run the demo on Safari and if you tap on one of the button you will see the ripple effect is not contained inside the button.

![screen shot 2015-05-04 at 4 54 09 pm](https://cloud.githubusercontent.com/assets/116360/7465111/a5ec50ba-f27f-11e4-8ea5-586f9737018b.png)

**Comment by cdata** [comment]
I'm worried that there is not a trivial solution to this. I ran into this a long time ago when I first started working on the ripple. See http://output.jsbin.com/temexa/4

**Comment by frankiefu** [comment]
Fixed by https://github.com/PolymerElements/paper-ripple/commit/6d23b41fad050ccb4527e5621799b4b0bfd85f9d
