### ISSUE TITLE
Unknown function in paper-button-behavior

### ISSUE THREAD

**Issue by Haardt** [PolymerElements/paper-button#60]
Hi,
this breaks the complete rendering in the current version(1.0.4):

```javascript
paper-button-behavior.html:59 Uncaught TypeError: this._setElevation is not a function
```

**Comment by notwaldorf** [comment]
Did you just update `paper-button`, without updating any of its dependencies? There were changes downstream that went along with this release. I thing doing a `bower install` should update all your dependencies and fix this.

(Please re-open if this doesn't in fact fix this)

**Comment by klarkc** [comment]
+1 Still happening.

paper-behavior latest version (1.0.11) do not have the _setElevation function.

The _setElevation function seems to be a private of paper-behavior. Maybe we need a public method to set elevation and be able to track breaking changes in that behavior.
