### ISSUE TITLE
first click/tab is ignored in firefox

### ISSUE THREAD

**Issue by bushuyev** [PolymerElements/paper-button#61]
First click/tab is ignored in firefox 41.0.1. See http://jsbin.com/gigako/1/edit?html,output, just a basic button. In ie and chrome wokrs ok.

**Comment by notwaldorf** [comment]
If you update `paper-ripple` to the latest version (a `bower install` in `paper-button` should do it), this should be fixed.

**Comment by bushuyev** [comment]
jsbin takes the button from http://polygit.org/polymer+:master/components/paper-button/paper-button.html - should be the latest.

**Comment by notwaldorf** [comment]
Yup, I see the tap on first click in the jsbin in FF.

**Comment by bushuyev** [comment]
yes, now I see it too. magic. sorry.

**Comment by notwaldorf** [comment]
Hah, no worries! :panda_face:
