### ISSUE TITLE
Why paper-button not extends button native element?

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-button#62]
Why `paper-button` not extends `button` native element?

**Comment by cdata** [comment]
`paper-button` is a living example of what can be built without relying on the native button behavior. However, this does not mean that you cannot get the same effect with a native button. It just means that for aesthetic reasons, we decided to implement it the way it is.

There are advantages and disadvantages to each choice. In all likelihood, we will eventually release a `<button is="paper-button">`-esque element at some point.

**Comment by abdonrd** [comment]
Thanks @cdata!
