### ISSUE TITLE
**CRITICAL** paper-button elements require two clicks in Firefox

### ISSUE THREAD

**Issue by triune** [PolymerElements/paper-button#65]
This is a particularly nuisance for all Firefox users as it may appear that paper-button elements are broken. A user may not be keen enough to recognize that a double-click is required as a workaround.

This errata began sometime in the last 2 weeks as this was not an issue before pulling in the latest changes from bower late last week for our project.

**Comment by notwaldorf** [comment]
This has already been fixed last week in a `paper-ripple` release. If you pull all dependencies again, it should be fixed.

**Comment by triune** [comment]
This is probably a n00b question, but shouldn't a bower update pull in the latest versions of all dependencies? Is there another command that would force an update beyond these? Clearing bower cache didn't help either.

**Comment by notwaldorf** [comment]
It should, but I don't know if you pulled the dependencies before or after the fix :)
`paper-ripple` v1.0.4 has the fix.

**Comment by triune** [comment]
Brilliant, thanks... yes, please close this issue as I can confirm it's fixed on my end for Firefox as well.
