### ISSUE TITLE
option for default form submit behaviors

### ISSUE THREAD

**Issue by jab** [PolymerElements/paper-button#69]
paper-button does not currently include an actual native button (or `<input type=submit>`) element. As a result, simply including a paper-button inside a form is not sufficient for being able to submit the form by pressing enter from one of the inputs. So currently, hooking this default behavior back up has to be done manually. Similarly, the click handler of a paper-button inside a form must currently be bound to the form's submit manually.

What if users could just write something like:
```html
<form>
  <!-- behavior 1: pressing enter while the cursor is in this input should submit the form -->
  <input name="name" required>
  <!-- behavior 2: clicking this button should submit the form -->
  <paper-button default-submit>
</form>
```
and that `default-submit` attribute would cause the default behaviors above to just work.

For behavior 1, it looks like simply including a native `<input type=submit hidden>` anywhere inside the form would do the trick. So could paper-button just add this element to its dom tree when `default-submit` is desired? Then, the paper-button's `onclick` could just call `click()` on the (hidden) native submit input to take care of behavior 2.

Note, I believe this is orthogonal to (but would nicely complement) PolymerElements/iron-form#46.

I'd be happy to try to work up a PR if there is interest. What do you think?

**Comment by notwaldorf** [comment]
I don't think this will work in the Shadow DOM. Since the hidden input is inside the paper-button's shadow DOM, it isn't visible to the form, so behaviour 1 won't actually work

**Comment by jab** [comment]
Thanks for taking a look @notwaldorf, and that's too bad. Is there another way to get this to work? Do you think this would be valuable to support?

**Comment by jab** [comment]
A possible workaround in the meantime: put `<paper-button>` inside a native `<button>`:

- [demo](http://output.jsbin.com/jiquno/6)
- [code](http://jsbin.com/jiquno/edit?html,output)

You have to add styles to the containing button so it doesn't show up, but still useful maybe.

**Comment by keanulee** [comment]
@jab I think that's a good workaround. Adding `<form>` compatibility to `<paper-button>` will add complexity (and performance cost) that wouldn't be needed for other use cases. Remember to also set `tabindex="-1"` in the wrapping `<button>` tag to make sure it can't get focus (since `<paper-button>` will receive focus anyways).

```html
<button style="border:none; background:none;" tabindex="-1">
  <paper-button raised>Submit</paper-button>
</button>
```

**Comment by jab** [comment]
Thanks @keanulee, great point!

@elegos, I just came across your https://github.com/elegos/paper-submit component. Thought you might be interested to know about the technique above, which doesn't require any javascript to accomplish the same thing.

**Comment by elegos** [comment]
Hello @jab thanks for pointing it out for me. In my humble opinion though, I prefer to write crystal-clear HTML documents (that's part of the web components idea). Adding a `paper-button` inside of a `button` means creating an ugly workaround.

Yes of course my solution is not perfect (in the end it creates a DOM element in any case), but at least the web designer doesn't have to bother about DOM artifacts by his/her own in the writing.

Last but not least you have to create a class for those buttons to "hide" them... Even though your idea is clever then, I'll stick with my paper-submit for now, hoping that paper-button will be able to submit forms one day :)

**Comment by jab** [comment]
I meant in case you could change your webcomponent to do this under the
hood, which would be much simpler than your implementation. But maybe I'm
missing something.

**Comment by elegos** [comment]
Yep, you're missing that a button has to be re-styled. You can't anticipate which CSS the developer will write for the `button` tag, not only the default styling. I remember in my tests I started out like you embedding the element inside a button, but ended up with that solution due to style problems :)

**Comment by jab** [comment]
Ah, too bad!
