### ISSUE TITLE
How to end the ripple animation

### ISSUE THREAD

**Issue by motss** [PolymerElements/paper-button#83]
In `paper-ripple`, there is a `upAction` method that can end the ripple animation loop. 
How can we do that in `paper-button` asince there is no `upAction` method?

**Comment by keanulee** [comment]
Hi @motss,

You can programmatically access `<paper-button>'s <paper-ripple>` by using `getRipple()` (defined in https://github.com/PolymerElements/paper-behaviors/blob/master/paper-ripple-behavior.html#L99)to call its methods:

```javascript
var button = document.querySelector('paper-button');
var ripple = button.getRipple();
ripple.downAction();
ripple.upAction;
```
