### ISSUE TITLE
bower install PolymerElements/paper-button#1.0.11 doesn't work

### ISSUE THREAD

**Issue by rhashimoto** [PolymerElements/paper-button#84]
I can't use bower 1.7.2 to install either paper-button with no version or explicitly 1.0.11, e.g.:

    /var/tmp $ mkdir foo
    /var/tmp $ cd foo
    /var/tmp/foo $ bower install PolymerElements/paper-button
    bower cached        git://github.com/PolymerElements/paper-button.git#1.0.11
    bower validate      1.0.11 against git://github.com/PolymerElements/paper-button.git#*
    bower install       paper-button#1.0.11

    paper-button#1.0.11 components/paper-button
    /var/tmp/foo $ ls -al components/paper-button
    total 1
    drwxr-xr-x   5 roy            wheel    170 2016-01-02 13:31 .
    drwxr-xr-x   3 roy            wheel    102 2016-01-02 13:31 ..
    -rw-r--r--   1 roy            wheel    428 2016-01-02 13:31 .bower.json
    -rw-r--r--   1 roy            wheel     17 2015-12-09  2015 .gitignore
    -rw-r--r--   1 roy            wheel    172 2016-01-02 11:50 .travis.yml

No error is reported from bower but necessary files are missing, e.g. `paper-button.html`. It works if I explicitly install `PolymerElements/paper-button#1.0.10`.

**Comment by notwaldorf** [comment]
I just ran `bower install polymerelements/paper-button` in a fresh directory, and it downloaded `paper-button` correctly (v 1.0.11). Since it's saying it's cached, maybe run `bower cache clean` first?

**Comment by rhashimoto** [comment]
Ah yes, `bower cache clean` does make things work. Thanks, I'm closing!
