### ISSUE TITLE
No font by default

### ISSUE THREAD

**Issue by tyrsensei** [PolymerElements/paper-button#86]
Hello,

I'm quite new to Polymer, and I wanted to test the `paper-button` element. I already tried the `paper-input` element without any problem (Roboto font applied by default).

When initiating a paper-button, it seems that it doesn't take into account any typography. Indeed, I only get the default `Times New Roman` font on the button (but the behavior of the button is correct).

Looking at the docs, I see that it's the shared `demo-pages-shared-styles` that enables the roboto font.

I don't really know if it's an OK behavior or not, but the fact that `paper-input` and `paper-button` work differently puzzles me.

Thanks in advance for your answers.

**Comment by dsschnau** [comment]
Agreed... I came across this trying to demo using a `paper-button` with minimal imports. I'm surprised its not Roboto on it own.

**Comment by notwaldorf** [comment]
Yeah, this is a long standing issue. The difference between the two elements is that `paper-button` gets its content from the light dom (i.e. you are creating the content and responsible for styling it), whereas `paper-input` creates and styles all its content.

I believe that @valdrinkoshi is on a mission to standardize these, though.
