### ISSUE TITLE
Non-standard code: Javascript code in the <script> tag is showing up after the end of the </dom-module> tag

### ISSUE THREAD

**Issue by cherukumilli** [PolymerElements/paper-button#88]
paper-button's code is not following the same standards as other elements. paper-button's javascript code is in the <script> ...</script> tag but this <script> section appears after the end of the </dom-module> tag. All other elements have the <script>...</script> before the </dom-module>

### Current paper-button code:
```
...
<dom-module>
   ...
</dom-module>
<script>
   ...
</script>
```

### Expected:
```
...
<dom-module>
   ...
   <script>
      ...
   </script>
</dom-module>
```

**Comment by keanulee** [comment]
Hi @cherukumilli,

Thanks for letting us know. Would you mind creating a PR for this?

**Comment by abdonrd** [comment]
PR: https://github.com/PolymerElements/paper-button/pull/93

**Comment by keanulee** [comment]
Thanks @abdonrd
