### ISSUE TITLE
Paper Button element is not working in Google Chrome But Works fine In Firefox

### ISSUE THREAD

**Issue by shivarajnaidu** [PolymerElements/paper-button#92]
The `paper-button` element not working in **_Google chrome but works well in Firefox**_

> _( with **webcomponents flag enabled, failed ** to work in firefox also ..) _

**I am using firefox 42 and google chrome  46.0.2490.71** 

## Expected Result

Proper working of paper-button element display on google chrome and firefox with webcomponents enabled...

#### This output is taken from firefox
(without web components enabled) and working as expected..

![selection_2016012217 25 57](https://cloud.githubusercontent.com/assets/12374494/12510167/e477e736-c12d-11e5-98a2-f9bfbed732f9.jpg)

#### This output is taken from google chrome

(failed to work properly , ** just displaying text** )

![selection_2016012119 01 07](https://cloud.githubusercontent.com/assets/12374494/12510075/19fddc72-c12d-11e5-80e8-48729c5f23bd.jpg)

and 

#### This output is taken from firefox (with webcomponents flag enabled)

![selection_2016012217 36 59](https://cloud.githubusercontent.com/assets/12374494/12510293/dbc33536-c12e-11e5-9b67-a78e10cfbfec.jpg)

## Steps to reproduce

```html
<!DOCTYPE html>
<html>
  <head>
    <!-- 1. Load webcomponents-lite.min.js for polyfill support. -->
    <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js">
    </script>

    <!-- 2. Use an HTML Import to bring in some elements. -->
    <link rel="import" href="bower_components/paper-button/paper-button.html">
    
  </head>
  <body>
    
    <paper-button>link</paper-button>
<paper-button raised>raised</paper-button>
<paper-button toggles raised>toggles</paper-button>
<paper-button disabled>disabled</paper-button>

  </body>
</html>
```

1. This is html markup i used

2. Run this in firefox (works fine)

3 Run inside google chrome or firefox with wecomponents enabled(failed to work properly)

### My Thought About This Issue

>   I think `paper-button` testing failed in firefox because of web components flag enabled in firefox  and also failed in google chrome for the same web components .. But i am not sure about this.. this is just what i  thought about this... 

<b> Expecting Reason and Best Solution for this Issue to be Resolved and Documentation for Using Polymer elements is Not enough and not clear to try newbies .. please improve it  </b>

**Comment by keanulee** [comment]
Hi @shivarajnaidu ,

Due to CORS headers, you need to use a web server to serve files (instead of using "file://" URLs). The code you provided works as expected when using a web server.

http://jsbin.com/varixeyedu/edit?html,output

**Comment by shivarajnaidu** [comment]
How can I accomplish same in my local computer for testing.. Can I do this with nodejs or I need any webserver like appachee

**Comment by shivarajnaidu** [comment]
And if it happens due to CORS then how its working well on firfox (please see my issue fully once again) 

@keanulee

**Comment by shivarajnaidu** [comment]
Sir, Please Reopen this issue 
@keanulee

**Comment by keanulee** [comment]
Please get a copy of the paper-button repo (e.g. `git clone` or download ZIP) and follow the same steps as https://github.com/PolymerElements/seed-element/blob/master/README.md

**Comment by shivarajnaidu** [comment]
:+1: 
@keanulee

**Comment by shivarajnaidu** [comment]
And if it happens due to CORS then how its working well on firfox ?
How it works on Firefox??
