### ISSUE TITLE
Paper-button doesn't use a proper font style

### ISSUE THREAD

**Issue by jhrdina** [PolymerElements/paper-button#94]
I feel like paper-button should use [paper-styles/typography.html](https://github.com/PolymerElements/paper-styles/blob/master/typography.html) and its `--paper-font-button` mixin for font.

## Expected outcome

Paper button uses 14px font with `font-weight: 500` (Roboto Medium) as mentioned in [Google Design Spec's Typography section](https://www.google.com/design/spec/style/typography.html#typography-styles) and is already defined in [paper-styles/typography.html](https://github.com/PolymerElements/paper-styles/blob/master/typography.html).

![after](https://cloud.githubusercontent.com/assets/1280734/12544023/12768836-c336-11e5-817f-95af6e3d749a.png)

*Image: material-design-lite [demo](http://www.getmdl.io/templates/dashboard/#), their CSS implementation [here](https://github.com/google/material-design-lite/blob/master/src/button/_button.scss)*

## Actual outcome

Paper button uses default font size with default font-weight (400 - Roboto Regular).

![before](https://cloud.githubusercontent.com/assets/1280734/12544024/148ca088-c336-11e5-8164-9893c137054a.png)

*Image: paper-card [demo](https://elements.polymer-project.org/elements/paper-card?view=demo:demo/index.html&active=paper-card)*

**Comment by abdonrd** [comment]
:+1:

**Comment by abdonrd** [comment]
PR about this: https://github.com/PolymerElements/paper-button/pull/96

**Comment by blasten** [comment]
cc @notwaldorf

**Comment by keanulee** [comment]
See https://github.com/PolymerElements/paper-button/issues/95#issuecomment-176444072
