### ISSUE TITLE
Focused paper-button can fire "click" event, even after becoming disabled

### ISSUE THREAD

**Issue by nick211** [PolymerElements/paper-button#98]
Actual behavior: If a paper-button becomes disabled while focused, and the user presses the "enter" key, the paper-button will fire a "click" event.
Expected behavior: no event is fired.

Steps to reproduce:
http://jsbin.com/felahuhezo/edit?html,output
1. Before the timer expires, click one of the paper buttons to focus it, and dismiss the alert.
2. Wait for the timeout to expire and all buttons to become disabled.
3. Hit "enter" key.
4. Another alert is shown.

Note how this behavior is different for the system `<button>`, which does not show another alert.

Tested on Chrome.

**Comment by notwaldorf** [comment]
Yup, sounds like a bug.
