### ISSUE TITLE
:host > ::content * selector doesn't make sense

### ISSUE THREAD

**Issue by esprehn** [PolymerElements/paper-button#99]
there's only one `<content>` in the shadow root, and it's always a child of the host for matching, so this doesn't really make sense, why not just write `::content *` ? Also note that Shadow DOM v1 will not allow a descendant selector like this. I'm not sure what this code was trying to do, but in v1 the best you could do is `::slotted(*)` I think which is only `::content > *` and doesn't deeply style slotted nodes.

**Comment by esprehn** [comment]
More importantly, what is this code trying to do?

**Comment by keanulee** [comment]
Hi @esprehn 

Seems like this rule is not really needed (probably legacy code). Mind sending a PR to remove this? Thanks.

**Comment by notwaldorf** [comment]
Heh, I don't think @esprehn will send a PR; somebody else should take care of it :)
